### ISSUE TITLE
About as new homepage

### ISSUE THREAD

**Issue by rickymccallum87** [CoderDojoDC/CoderDojoDC.github.io#15]
Quickest fix to keep the site from looking outdated is to move the blog off of the homepage, since there are no new posts.

- [ ] Move current ~/index.html to ~/blog/blog.html
- [ ] Rename ~/about/index.md to ~/index.md
- [ ] Remove About link from navigation (header image will now link there)
- [ ] Change title (in index.md front matter) from About to CoderDojoDC

Should a blog link be added to the nav, or would that be redundant with archive?

**Comment by jwestgard** [comment]
This sounds like exactly the right approach.  I wouldn't want to lose the old posts, so if we can relocate them, keep the option of blog posting, and make the about page the main splash page, that strikes me as the optimal solution.

**Comment by fhunleth** [comment]
Since blog looked the same as archive, I didn't bother adding it. We may want to rename archive to blog if we start blogging again.
